insert into role(name) VALUES ('user');
insert into role(name) VALUES ('guest');
insert into role(name) VALUES ('administrator');
insert into rules(name) VALUES ('public');
insert into rules(name) VALUES ('private');
insert into users(name, role_id) VALUES ('Ivan', 1);
insert into users(name, role_id) VALUES ('Oleg', 2);
insert into users(name, role_id) VALUES ('Petr', 3);
insert into rolerules (role_id, rules_id) VALUES (1, 1);
insert into rolerules (role_id, rules_id) VALUES (2, 1);
insert into rolerules (role_id, rules_id) VALUES (3, 2);
insert into category(name) VALUES ('standart');
insert into category(name) VALUES ('premium');
insert into category(name) VALUES ('social');
insert into state(name) VALUES ('begining');
insert into state(name) VALUES ('error');
insert into state(name) VALUES ('ended');
insert into item(name, users_id, category_id, state_id) VALUES ('First_Item', 1, 1, 1);
insert into item(name, users_id, category_id, state_id) VALUES ('Second_Item', 2, 2, 2);
insert into item(name, users_id, category_id, state_id) VALUES ('Third_Item', 3, 3, 3);
insert into comments(comment, item_id) VALUES ('close', 1);
insert into attachs(name, item_id) VALUES ('attachment', 1);
insert into attachs(name, item_id) VALUES ('attachment2', 2);
insert into attachs(name, item_id) VALUES ('attachment3', 3);